version: '3'
services:

  todo-app:
    image: devops77.azurecr.io/todo-app:1.1  #todo-app
    ports: 
      - "3000:3000"

  todo-mongo-local1:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin 
      MONGO_INITDB_ROOT_PASSWORD: pass

  mongo-express-local1:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
      ME_CONFIG_MONGODB_SERVER: todo-mongo-local1